"""Add comment field to invoice

Revision ID: 350ed41b31ad
Revises: 
Create Date: 2025-04-24 22:05:54.536990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350ed41b31ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
